version: '3.0'

services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.0.3
    ports:
      - "27017:27017"

  redis:
    image: redis:4.0.11-alpine
    ports:
      - "6379:6379"
